name: pacoaguayo
favicon: null
layout_spectrum: 0.005560185294598341
typography_spectrum: 0.15300930733792484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5893370849080384
  lightness: 0.5709681583102793
  saturation: 0.4513802258297801
  rhythmicContrast: 0.3624880544375628
purpose: []
