name: pacoaguayo
favicon: null
layout_spectrum: 0.005560185294598341
typography_spectrum: 0.15300930733792484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ece9'
    - '#202e1e'
    - '#7e7766'
    - '#fa602c'
    - '#831812'
  brandStrength: 0.5625
  lightness: 0.5709681583102793
  saturation: 0.4513802258297801
  rhythmicContrast: 0.3624880544375628
purpose: []
